CREATE TABLE `fs_news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `summary` text DEFAULT NULL,
  `content` longtext DEFAULT NULL,
  `tags` varchar(255) DEFAULT NULL,
  `category_id` int(11) DEFAULT NULL,
  `category_alias` varchar(255) DEFAULT NULL,
  `category_name` varchar(255) DEFAULT NULL,
  `category_id_wrapper` varchar(255) DEFAULT NULL,
  `category_alias_wrapper` varchar(255) DEFAULT NULL,
  `category_published` int(11) DEFAULT NULL,
  `title` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `alias` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `video` varchar(255) DEFAULT NULL,
  `creator` varchar(255) DEFAULT NULL,
  `source_website` varchar(255) DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `editor` varchar(255) DEFAULT NULL,
  `show_in_homepage` tinyint(4) DEFAULT 0,
  `is_slide` tinyint(4) DEFAULT 0,
  `is_new_video` tinyint(4) DEFAULT 0,
  `is_video` tinyint(4) DEFAULT 0,
  `hits` int(11) NOT NULL DEFAULT 0,
  `published` tinyint(4) DEFAULT NULL,
  `ordering` int(11) DEFAULT NULL,
  `title_display` varchar(255) DEFAULT NULL,
  `display_title` tinyint(4) NOT NULL DEFAULT 1,
  `display_column` int(11) DEFAULT NULL,
  `tags_group` int(11) DEFAULT NULL,
  `rating_count` int(11) DEFAULT NULL,
  `rating_sum` int(11) DEFAULT NULL,
  `keywords` varchar(255) DEFAULT NULL,
  `seo_title` varchar(255) DEFAULT NULL,
  `seo_keyword` varchar(255) DEFAULT NULL,
  `seo_description` longtext DEFAULT NULL,
  `is_new` tinyint(4) DEFAULT 0,
  `is_hot` tinyint(4) DEFAULT 0,
  `comments_total` int(11) DEFAULT 0,
  `comments_unread` int(11) DEFAULT 0,
  `comments_last_time` datetime DEFAULT NULL,
  `comments_published` int(11) DEFAULT 0,
  `products_related` varchar(255) DEFAULT NULL,
  `action_time` datetime DEFAULT NULL,
  `action_username` varchar(255) DEFAULT NULL,
  `action_id` int(11) DEFAULT NULL,
  `action_name` varchar(255) DEFAULT NULL,
  `news_related` varchar(255) DEFAULT NULL,
  `source_news` varchar(255) DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `author_last` varchar(255) DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `author_id` int(11) DEFAULT NULL,
  `author_last_id` int(11) DEFAULT NULL,
  `optimal_seo` tinyint(4) DEFAULT 0,
  `actflg` varchar(1) DEFAULT 'A',
  `ctdusr` varchar(5) DEFAULT NULL,
  `ctdwks` varchar(15) DEFAULT NULL,
  `ctddtm` datetime DEFAULT NULL,
  `mdfusr` varchar(5) DEFAULT NULL,
  `mdfwks` varchar(15) DEFAULT NULL,
  `lstmdf` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `cdtpgm` varchar(20) DEFAULT NULL,
  `mdfpgm` varchar(20) DEFAULT NULL,
  `file_upload` varchar(255) DEFAULT NULL,
  `other_languages1` varchar(255) DEFAULT NULL,
  `tawk_to` longtext DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1627 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC;
