model_list:
  - model_name: qwen3.5-35b
    litellm_params:
      model: openai/qwen3.5:35b-fast
      api_base: http://localhost:11434/v1
      api_key: "ollama"
    model_info:
      max_tokens: 16384
      max_input_tokens: 16384
      max_output_tokens: 16384

litellm_settings:
  set_verbose: true
  drop_params: true
